name: "Build Docker image"

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "main/**"
      - go.mod
      - go.sum
      - Dockerfile
      - .github/workflows/build_image.yml

env:
  CONTAINER_REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      digest: ${{ steps.build-image.outputs.digest }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Define image name suffix if necessary
        if: ${{ github.event_name == 'pull_request' }}
        id: image_suffix
        run:
          echo ::set-output name=image_suffix::-test

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}${{ steps.image_suffix.outputs.image_suffix }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        id: build-image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-digest:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' }}
    needs: build
    steps:
      - name: Check out k3s_gcp
        uses: actions/checkout@v3
        with:
          repository: ikanago/k3s_gcp
          ref: update-image-digest
          fetch-depth: 0

      - name: Update image digest
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          IMAGE=${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}@${{ needs.build.outputs.digest }}
          yq -i '(.spec.containers[] | select(.name=="akane") | .image) = "$IMAGE"' akane/pod.yaml
          git commit -am "Update image digest"

      - uses: ad-m/github-push-action@master

      - name: Create PR updating the image
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "Update image digest"
